### ISSUE TITLE
交易助手的功能

### ISSUE THREAD

**Issue by unbelievable2020** [Gary-Hertel/PureQuant#2]
感觉交易助手的功能需要改进。
比如网格交易，判断在哪个位置后，如果想挂单，不能开交易助手超时委托功能，只想在那个价格吃单。
就是想买的时候不使用，而卖的时候使用。

**Comment by bitkitty1** [comment]
在配置文件中就可以设置的啊，你不看视频教程或者使用文档吗？

**Comment by bitkitty1** [comment]
配置文件可以设置是否启用交易助手。你说的买的时候不用，卖的时候启用，目前不能设置，我个人觉得还是统一点比较好。你这个建议我会记录下来的，后续看情况再决定。

**Comment by Gary-Hertel** [comment]
目前不支持买卖分开设置是否启用交易助手，这个建议我先记录下来，以后看情况吧。
